repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.5 # Use the latest version
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pycqa/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        name: bandit
        exclude: ^tests/
        args:
          - -r

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-django

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest tests
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.9
    hooks:
      - id: pip-compile
        name: Compile requirements.txt from pyproject.toml
        args: [
            "pyproject.toml",
            "--output-file",
            "requirements.txt",
            "--no-reuse-hashes", # Omit hashes as requested
            "--quiet",
          ]
        files: ^pyproject\.toml$