repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.4 # Use the latest version
    hooks:
      # Runs the linter and auto-fixes any fixable errors
      - id: ruff
        args: [--fix]
      # Runs the formatter (alternative to black and isort)
      - id: ruff-format

  - repo: https://github.com/rtts/djhtml
    rev: 3.0.10
    hooks:
      - id: djhtml

  # bandit - find common security issues
  - repo: https://github.com/pycqa/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        name: bandit
        exclude: ^tests/
        args:
          - -r

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest tests
        language: system
        types: [python]
        pass_filenames: false

  # prettier - formatting JS, CSS, JSON, Markdown, ...
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        exclude: ^uv.lock

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.9
    hooks:
      # Use the 'pip-compile' hook ID to generate from pyproject.toml
      - id: pip-compile
        name: Compile requirements.txt from pyproject.toml
        args: [
            "pyproject.toml",
            "--output-file",
            "requirements.txt",
            "--no-reuse-hashes", # Omit hashes as requested
            "--quiet",
          ]
        # Run only if pyproject.toml changes
        files: ^pyproject\.toml$
